name: growlog-ide
services:
  backend:
    image: gradle:jdk21
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

    working_dir: /app
    command:
      [ "tail", "-f", "/dev/null" ]
    depends_on:
      db:
        condition: service_healthy
      rabbitmq: # RabbitMQ ì»¨í…Œì´ë„ˆê°€ ë¨¼ì € ì‹œì‘í•˜ë„ë¡ ì„¤ì •
        condition: service_started

  db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 10

  rabbitmq: # ğŸ’¡ RabbitMQ ì„œë¹„ìŠ¤ ì¶”ê°€
    image: rabbitmq:management
    ports:
      - "5672:5672" # AMQP í¬íŠ¸
      - "15672:15672" # ê´€ë¦¬ì UI í¬íŠ¸
    environment:
      - RABBITMQ_DEFAULT_USER=admin # ğŸ’¡ admin ê³„ì •ìœ¼ë¡œ ì„¤ì •
      - RABBITMQ_DEFAULT_PASS=admin # ğŸ’¡ admin ê³„ì •ìœ¼ë¡œ ì„¤ì •
      - RABBITMQ_LOOPBACK_USERS=none # ğŸ’¡ ì›ê²© ì ‘ì† í—ˆìš©

volumes:
  mysql_data:
