spring:
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/${RDS_DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&connectTimeout=10000&socketTimeout=10000&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_DB_USER_NAME}
    password: ${RDS_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  email:
    from: ${MAIL_FROM} #커스텀 클래스에서 사용하는 값

  cloud:
    aws:
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      region:
        static: ${S3_REGION}  # 버킷의 리전
      s3:
        bucket: ${S3_BUCKET_NAME}   # 버킷 이름
      stack:
        auto: false

  kakao:
    oauth:
      rest-api-key: ${KAKAO_REST_API_KEY}
      redirect-uri: ${KAKAO_REDIRECT_URI}
    redirect-front: https://growlog-web-ide.vercel.app/auth/kakao/success

  rabbitmq:
    host: ${RABBITMQ_HOST} # Amazon MQ 엔드포인트 주소 (amqps:// 제외)
    port: 5672             # AMQPS 기본 포트
    username: ${RABBITMQ_USER} # Amazon MQ 사용자 이름
    password: ${RABBITMQ_PASS} # Amazon MQ 비밀번호
    ssl:
      enabled: false         # 보안 연결 사용


efs:
  base-path: /mnt/efs/projects
  templates-path: /mnt/efs/templates
